-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
    -   id: requirements-txt-fixer
    -   id: check-ast
        language_version: python3
-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v1.9.1
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        language_version: python3
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v1.0.1
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: git://github.com/FalconSocial/pre-commit-mirrors-pep257
    rev: v0.3.3
    hooks:
    -   id: pep257
        args:
        - --ignore=D301,D203
        language_version: python3
